version: "3.9"

services:
  luminus:
    image: "luminus/build:latest"
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: /home/idvlab/Git/mkluminus
        target: /luminus
        read_only: false

#volumes:
#  appdata:
#    name: "luminus-appdata"
